# Generated by Django 5.0.14 on 2025-06-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0005_remove_documento_declaracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldeclaracion',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
