# Generated by Django 5.0.14 on 2025-06-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0006_alter_declaracion_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedeclaracion',
            name='anio_fiscal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedeclaracion',
            name='mes_fiscal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpedientedeclaracion',
            name='anio_fiscal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpedientedeclaracion',
            name='mes_fiscal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
