# Generated by Django 5.0.14 on 2025-05-06 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0006_alter_despacho_archivo_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('referencia_interna', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('declaracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='importaciones.declaracion')),
            ],
        ),
    ]
