# Generated by Django 5.0.14 on 2025-05-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0007_declaracion_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracion',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='declaracion',
            unique_together={('numero', 'anio')},
        ),
    ]
