# Generated by Django 5.0.14 on 2025-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0007_expedientedeclaracion_anio_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedeclaracion',
            name='folio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpedientedeclaracion',
            name='folio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
