# Generated by Django 5.0.14 on 2025-05-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0008_declaracion_anio_alter_declaracion_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='declaracion',
            table='declaracion',
        ),
        migrations.AlterModelTable(
            name='documento',
            table='documento',
        ),
    ]
