# Generated by Django 5.0.14 on 2025-06-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0008_expedientedeclaracion_folio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedeclaracion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalexpedientedeclaracion',
            name='tipo',
        ),
    ]
