# Generated by Django 5.0.14 on 2025-06-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0009_remove_expedientedeclaracion_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedeclaracion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='importaciones.tipodocumento'),
        ),
        migrations.AddField(
            model_name='historicalexpedientedeclaracion',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='importaciones.tipodocumento'),
        ),
    ]
