# Generated by Django 5.0.14 on 2025-05-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0010_documento_hash_archivo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['hash_archivo'], name='documento_hash_ar_22fe99_idx'),
        ),
    ]
