# Generated by Django 5.0.14 on 2025-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0010_expedientedeclaracion_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedeclaracion',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpedientedeclaracion',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
