# Generated by Django 5.0.14 on 2025-06-14 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0011_expedientedeclaracion_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedeclaracion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='importaciones.documento'),
        ),
    ]
