# Generated by Django 5.0.14 on 2025-05-06 05:58

import importaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0011_documento_documento_hash_ar_22fe99_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=importaciones.models.ruta_documento),
        ),
    ]
