# Generated by Django 5.0.14 on 2025-06-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0011_expedientedeclaracion_empresa_and_more'),
        ('importaciones', '0012_alter_documento_archivo'),
    ]

    operations = [
    ]
