# Generated by Django 5.0.14 on 2025-06-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0014_declaracion_created_date_declaracion_deleted_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedeclaracion',
            name='nota_ingreso',
        ),
        migrations.RemoveField(
            model_name='expedientedeclaracion',
            name='orden_compra',
        ),
    ]
