# Generated by Django 5.0.14 on 2025-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0019_remove_expedientedeclaracion_nota_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedeclaracion',
            name='nota_ingreso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expedientedeclaracion',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpedientedeclaracion',
            name='nota_ingreso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpedientedeclaracion',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
