# Generated by Django 5.0.14 on 2025-06-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0022_expedientedeclaracion_nota_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedeclaracion',
            name='nota_ingreso',
        ),
        migrations.RemoveField(
            model_name='expedientedeclaracion',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='historicalexpedientedeclaracion',
            name='nota_ingreso',
        ),
        migrations.RemoveField(
            model_name='historicalexpedientedeclaracion',
            name='orden_compra',
        ),
    ]
