# Generated by Django 5.0.14 on 2025-07-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0024_expedientedeclaracion_nota_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciondespacho',
            name='precio_estiba',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
