# Generated by Django 5.2.5 on 2025-09-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0025_configuraciondespacho_precio_estiba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
