# Generated by Django 5.2.5 on 2025-09-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0026_alter_ordencompra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
