# Generated by Django 5.2.5 on 2025-10-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0027_alter_ordencompra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciondespacho',
            name='precio_prod',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
