# Generated by Django 5.2.5 on 2025-10-24 22:04

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0031_alter_producto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),


        migrations.AlterField(
            model_name='declaracion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='expedientedeclaracion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='expedientedeclaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='expedientedeclaracion',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaracion',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaracion',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalexpedientedeclaracion',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalexpedientedeclaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalexpedientedeclaracion',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('codigo_producto', models.CharField(max_length=255)),
                ('proveedor_marca', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='importaciones.empresa', verbose_name='Empresa Propietaria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
