# Generated by Django 5.2.5 on 2025-10-24 22:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0032_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_de_actualizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_de_creacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='importaciones.empresa', verbose_name='Empresa Propietaria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
