# Generated by Django 5.2.5 on 2025-10-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0034_alter_declaracion_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='expedientedeclaracion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='expedientedeclaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='expedientedeclaracion',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaracion',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaldeclaracion',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalexpedientedeclaracion',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalexpedientedeclaracion',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalexpedientedeclaracion',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
    ]
