# Generated by Django 5.0.14 on 2025-06-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_passwordresettoken_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='password_reset_token',
        ),
    ]
