# Generated by Django 5.2.5 on 2025-10-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_direccion_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaldireccion',
            name='created_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaldireccion',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaldireccion',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='created_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='created_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
    ]
