# Generated by Django 5.2.5 on 2025-11-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_almacen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacymovalmcab',
            name='cadirenv',
            field=models.TextField(blank=True, db_column='CADIRENV', null=True),
        ),
    ]
